language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-parse' ]; then cd .. && eval "mv $currentfolder generator-angular-parse" && cd generator-angular-parse; fi

